### ISSUE TITLE
keep case

### ISSUE THREAD

**Issue by yukulele** [ekwoka/eslint-plugin-filename-export#2]
Hi, Is it possible to add an option to force filename to keep export name case?

**Comment by ekwoka** [comment]
As in have strict casing?

For sure

🤔 Probably as a configuration option

**Comment by ekwoka** [comment]
Completed with: https://github.com/ekwoka/eslint-plugin-filename-export/commit/98726478af478a839630ee7711d82f4c56e10792

Pushed live in v 0.3.0
