### ISSUE TITLE
What if the filename contains "-" or "_"

### ISSUE THREAD

**Issue by kenberkeley** [ekwoka/eslint-plugin-filename-export#4]
If ⬇️

```json
"filename-export/match-named-export": "error"
```

then the following example will be complained `error  Filename does not match any named exports`

```ts
// hello_world.ts
export function helloWorld() {}
```

**Comment by ekwoka** [comment]
This should be fixed in `0.4.0` from 2 days ago.

Please update and see if that solved the issue.

**Comment by kenberkeley** [comment]
I am actually using 0.4.0...

**Comment by ekwoka** [comment]
Oh right, it's because of the extra character.

It's an uncommon naming scheme for sure...

**Comment by kenberkeley** [comment]
Underscore is actually a very common character in file naming. e.g. “node_modules” 😂

**Comment by kenberkeley** [comment]
I ended up using https://github.com/epaew/eslint-plugin-filenames-simple/blob/master/docs/rules/named-export.md so don’t wanna waste your time on this.

**Comment by ekwoka** [comment]
@kenberkeley but I fixed is here: https://github.com/ekwoka/eslint-plugin-filename-export/pull/5

with `0.5.0`

**Comment by kenberkeley** [comment]
Awesome thanks @ekwoka
